import streamlit as st
import requests

# PAGE CONFIG
st.set_page_config(page_title="Fraud Risk Analyser", page_icon="🔍", layout="centered")

# HEADER
st.title("🔍 Fraud Risk Analyser")
st.markdown(
    "**Internal Analyst Tool** — Enter transaction details from the payment record to generate an instant fraud risk assessment."
)
st.divider()

# API URL
API_URL = "https://fraud-detection-api-tg28.onrender.com/predict"

# DATASET DISCLOSURE
st.info(
    "This tool is built on the IEEE-CIS dataset using Vesta Corporation's proprietary transaction signals. "
    "In production, equivalent signals would be generated by the bank's internal feature engineering pipeline."
)

# PRE-FILLED EXAMPLE TRANSACTIONS
LEGIT_EXAMPLE = {
    "transaction_amt": 45.0,
    "product_cd": 4,
    "card3": 150,
    "c12": 1.0,
    "c14": 5.0,
    "p_emaildomain": 50.0,
    "v317": 0.0,
}

FRAUD_EXAMPLE = {
    "transaction_amt": 2500.0,
    "product_cd": 0,
    "card3": 100,
    "c12": 25.0,
    "c14": 0.0,
    "p_emaildomain": 0.0,
    "v317": 100.0,
}

# INITIALISE SESSION STATE
if "defaults" not in st.session_state:
    st.session_state.defaults = {
        "transaction_amt": 150.0,
        "product_cd": 4,
        "card3": 150,
        "c12": 1.0,
        "c14": 1.0,
        "p_emaildomain": 10.0,
        "v317": 0.0,
    }

# EXAMPLE BUTTONS
st.subheader("Quick Examples")
col_ex1, col_ex2 = st.columns(2)
with col_ex1:
    if st.button("✅ Load Legitimate Example", use_container_width=True):
        st.session_state.defaults = LEGIT_EXAMPLE
        st.rerun()
with col_ex2:
    if st.button("🚨 Load Fraud Example", use_container_width=True):
        st.session_state.defaults = FRAUD_EXAMPLE
        st.rerun()

defaults = st.session_state.defaults

st.divider()
st.subheader("Transaction Details")

col1, col2 = st.columns(2)

with col1:
    transaction_amt = st.number_input(
        "Transaction Amount ($)",
        min_value=0.0,
        max_value=50000.0,
        value=float(defaults["transaction_amt"]),
        step=10.0,
        help="The dollar value of the transaction being assessed.",
    )
    card3 = st.number_input(
        "Card Type Code",
        min_value=100,
        max_value=300,
        value=int(defaults["card3"]),
        help="Numeric code identifying the card network from the payment system.",
    )
    c12 = st.number_input(
        "Recent Transaction Count",
        min_value=0.0,
        max_value=100.0,
        value=float(defaults["c12"]),
        step=1.0,
        help="Number of recent transactions linked to this card or account.",
    )

with col2:
    product_cd = st.selectbox(
        "Product Category",
        options=[0, 1, 2, 3, 4],
        index=int(defaults["product_cd"]),
        format_func=lambda x: [
            "C — Card Payment",
            "H — Home Goods",
            "R — Refund",
            "S — Service",
            "W — Web Direct",
        ][x],
        help="The category of purchase associated with this transaction.",
    )
    c14 = st.number_input(
        "Recent Account Activity Count",
        min_value=0.0,
        max_value=100.0,
        value=float(defaults["c14"]),
        step=1.0,
        help="Number of recent activity events linked to this account.",
    )
    p_emaildomain = st.number_input(
        "Purchaser Email Domain Code",
        min_value=0.0,
        max_value=200.0,
        value=float(defaults["p_emaildomain"]),
        step=1.0,
        help="Encoded identifier for the purchaser's email domain from the payment system.",
    )

st.divider()

# PREDICT BUTTON
if st.button("Run Risk Assessment", type="primary", use_container_width=True):

    payload = {
        "features": {
            "TransactionAmt": transaction_amt,
            "ProductCD": product_cd,
            "card3": card3,
            "C12": c12,
            "C14": c14,
            "P_emaildomain": p_emaildomain,
            "V317": defaults.get("v317", 0.0),
        }
    }

    with st.spinner(
        "Analysing transaction... (first request may take up to 60 seconds as the server wakes up)"
    ):
        try:
            response = requests.post(API_URL, json=payload, timeout=60)
            result = response.json()

            st.divider()
            st.subheader("Risk Assessment Result")

            risk_level = result["risk_level"]
            fraud_prob = result["fraud_probability"]
            is_fraud = result["is_fraud"]

            if is_fraud:
                if risk_level == "CRITICAL":
                    st.error("🚨 CRITICAL RISK — Recommend Immediate Block")
                elif risk_level == "HIGH":
                    st.error("🔴 HIGH RISK — Recommend Manual Review")
                else:
                    st.warning("🟡 MEDIUM RISK — Recommend Additional Verification")
            else:
                st.success("✅ LOW RISK — Transaction Clear to Approve")

            col3, col4, col5 = st.columns(3)
            with col3:
                st.metric("Fraud Probability", f"{fraud_prob*100:.1f}%")
            with col4:
                st.metric("Risk Level", risk_level)
            with col5:
                st.metric("Decision", "BLOCK" if is_fraud else "APPROVE")

            st.markdown("**Fraud Risk Score:**")
            st.progress(float(fraud_prob))

            st.subheader("Analyst Notes")
            st.text_area(
                "Add notes for case file (optional)",
                placeholder="Enter any additional observations about this transaction...",
            )

            with st.expander("View Raw API Response"):
                st.json(result)

        except Exception as e:
            st.error(f"API Error: {str(e)}")

st.divider()
st.caption(
    "Model: XGBoost | ROC-AUC: 0.9262 | Dataset: IEEE-CIS Fraud Detection | Threshold: 0.0563 | For Internal Use Only"
)